name: Deploy prod server

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install doctl 
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Build the server Docker image
      run: make buildserver
    - name: Log in to DO Container Registry 
      run: doctl registry login --expiry-seconds 600
    - name: Push the image to the registry
      run: make pushserver

